name: 'Pytest-Django CI - Docker'

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker images
        run: |
          docker compose -f ./docker-compose.yml -f ./docker-compose-ci.yml build
      - name: Run docker containers and tests
        run: |
          docker compose -f ./docker-compose.yml -f ./docker-compose-ci.yml up --abort-on-container-exit
